version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    wrap_in_directory: false
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

release:
  github:
    owner: bitrise-io
    name: bitrise-plugins-agent
  draft: false
  mode: replace

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Version }}"
