name: ai-reviewer
description: |-
  Bitrise plugin for reviewing code using AI.
  
  This plugin uses AI to analyze code changes and provide feedback.
version: 0.1.0

executable:
  osx: ./bin/ai-reviewer
  linux: ./bin/ai-reviewer

requirements:
- tool: bitrise
  min_version: 1.10.0
  max_version: ""

trigger: ""
