package common

import "fmt"

type LineLevel struct {
	File string `json:"file"`
	Line int    `json:"line"`
	Body string `json:"description"`
}

type LineLevelFeedback struct {
	Lines []LineLevel `json:"line-feedback"`
}

func (l LineLevel) Header(gitblame string) string {
	return fmt.Sprintf("<!-- bitrise-plugin-ai-reviewer: %s:%d:%s -->", l.File, l.Line, gitblame)
}

func (l LineLevel) String() string {
	return l.Body
}

func (l LineLevel) OverallReview() string {
	return "This review was generated by AI and may not be perfect.\n\nPlease review it carefully."
}
